SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

FPS = 60
MILLISECONDS = 1000

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_SPAWN_SPEED_BOOST = 1.2  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MIN_SPEED = 40
ASTEROID_MAX_SPEED = 100
ASTEROID_MIN_SPAWN_ANGLE = 20
ASTEROID_MAX_SPAWN_ANGLE = 20
ASTEROID_BASE_SCORE = 100

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOTING_SPEED = 500
PLAYER_RELOAD_RATE = 0.3
PLAYER_LIFES = 3
PLAYER_HIT_TIMER = 3

BULLET_RADIUS = 5

BLINKING_TIMER = 0.2
